Repository systemli/ticker-admin, pull requests merged in 2022-06, with the labels that each got.

#267 ♻️ Rewrite user related views to TypeScript
  .github/workflows/quality.yaml
  package.json
  src/api/Ticker.ts
  src/api/User.js
  src/api/User.ts
  src/components/TickersDropdown.js
  src/components/TickersDropdown.tsx
  src/components/UserForm.tsx
  src/components/UserList.js
  src/components/UserList.tsx
  src/components/UserListItem.tsx
  src/components/UserListItems.tsx
  src/components/UserModalDelete.tsx
  src/components/UserModalForm.tsx
  src/index.js
  src/views/UsersView.js
  src/views/UsersView.tsx
  yarn.lock
Labels: enhancement

#269 ♻️ Add App Component
  package.json
  src/App.tsx
  src/declaration.d.ts
  src/index.js
  src/index.tsx
  webpack.common.config.ts
  yarn.lock
Labels: enhancement

#270 ♻️ Rewrite Ticker related components to TypeScript
  package.json
  src/api/Ticker.ts
  src/components/Ticker.js
  src/components/TickerCard.tsx
  src/components/TickerForm.js
  src/components/TickerForm.tsx
  src/components/TickerList.js
  src/components/TickerList.tsx
  src/components/TickerListItem.tsx
  src/components/TickerListItems.tsx
  src/components/TickerModalDelete.tsx
  src/components/TickerModalForm.tsx
  src/models/Ticker.js
  src/utils/common.js
  src/views/HomeView.tsx
  src/views/TickerView.js
  yarn.lock
Labels: enhancement

#274 ⬆️ Upgrade Webpack related packages
  package.json
  webpack.dev.config.ts
  webpack.prod.config.ts
  yarn.lock
Labels: dependencies

#278 👷 Upgrade CI to use latest node versions
  .github/workflows/integration.yml
  .github/workflows/quality.yaml
  package.json
  yarn.lock
Labels: chore

#279 ➖ Remove unused dependencies
  package.json
  yarn.lock
Labels: dependencies

#272 ♻️ Rewrite Ticker View to TypeScript
  package.json
  src/App.tsx
  src/api/Message.js
  src/api/Message.ts
  src/components/Message.js
  src/components/Message.tsx
  src/components/MessageForm.js
  src/components/MessageForm.tsx
  src/components/MessageFormCounter.tsx
  src/components/MessageList.tsx
  src/components/MessageModalDelete.tsx
  src/lib/helper.ts
  src/views/TickerView.js
  src/views/TickerView.tsx
  yarn.lock
Labels: enhancement

#280 ♻️ Rewrite Authentication to TypeScript
  package.json
  src/App.tsx
  src/api/Auth.ts
  src/api/User.ts
  src/components/AuthService.js
  src/components/MessageList.tsx
  src/components/ProtectedRoute.tsx
  src/components/TickerList.tsx
  src/components/TickerListItem.tsx
  src/components/TickerListItems.tsx
  src/components/TickerResetButton.js
  src/components/TickerUserList.js
  src/components/TickersDropdown.tsx
  src/components/UserForm.tsx
  src/components/useAuth.tsx
  src/components/withAuth.js
  src/declaration.d.ts
  src/views/HomeView.tsx
  src/views/LoginView.tsx
  src/views/Navigation.tsx
  src/views/NotFoundView.tsx
  src/views/SettingsView.tsx
  src/views/TickerView.tsx
  src/views/UsersView.tsx
  yarn.lock
Labels: feature
