Repository systemli/ticker-admin, pull requests merged in 2022-07, with the labels that each got.

#282 ♻️ Rewrite User API
  src/api/User.ts
  src/components/UserForm.tsx
  src/components/UserList.tsx
  src/components/UserModalDelete.tsx
  src/components/useAuth.tsx
Labels: feature

#283 ♻️ Rewrite Ticker User List to TypeScript
  src/api/Ticker.ts
  src/components/TickerUserAddForm.tsx
  src/components/TickerUserCard.tsx
  src/components/TickerUserList.js
  src/components/TickerUserList.tsx
  src/components/TickerUserListItem.tsx
  src/components/TickerUserModalAdd.tsx
  src/components/TickerUserModalDelete.tsx
  src/views/TickerView.tsx
Labels: feature

#284 :recycle: Rewrite Reset Ticker Button to TypeScript
  src/api/Ticker.ts
  src/components/MessageForm.tsx
  src/components/MessageModalDelete.tsx
  src/components/TickerResetButton.js
  src/components/TickerResetModal.tsx
  src/views/TickerView.tsx
Labels: feature

#285 ♻️ Rewrite API Calls & Remove AuthService
  src/api/Message.ts
  src/api/Settings.ts
  src/api/Ticker.ts
  src/api/Upload.js
  src/api/Upload.ts
  src/components/AuthService.js
  src/components/InactiveSettingsCard.tsx
  src/components/InactiveSettingsForm.tsx
  src/components/MessageForm.tsx
  src/components/MessageList.tsx
  src/components/MessageModalDelete.tsx
  src/components/RefreshIntervalCard.tsx
  src/components/RefreshIntervalForm.tsx
  src/components/TickerForm.tsx
  src/components/TickerList.tsx
  src/components/TickerModalDelete.tsx
  src/components/TickersDropdown.tsx
  src/views/TickerView.tsx
Labels: feature

#286 🐛 Fix closing modal after message deleted
  src/api/Message.ts
  src/components/MessageModalDelete.tsx
Labels: bug

#287 ♻️ Rewrite LocationSearch to TypeScript
  src/components/LocationSearch.js
  src/components/LocationSearch.tsx
  src/components/TickerForm.tsx
Labels: feature

#290 ♻️ Rewrite Message Attachments to TypeScript
  src/api/Upload.ts
  src/components/MessageAttachmentsButton.tsx
  src/components/MessageAttachmentsPreview.tsx
  src/components/MessageForm.tsx
Labels: feature

#291 ♻️ Rewrite Maps for Messages to TypeScript
  src/components/EditMapModal.js
  src/components/Message.tsx
  src/components/MessageForm.tsx
  src/components/MessageList.tsx
  src/components/MessageMap.tsx
  src/components/MessageMapModal.tsx
Labels: feature

#289 :recycle: Rewrite Twitter Card to TypeScript
  package.json
  src/api/Ticker.ts
  src/components/TickerCard.tsx
  src/components/TickerResetModal.tsx
  src/components/TwitterCard.js
  src/components/TwitterCard.tsx
  src/views/TickerView.tsx
  yarn.lock
Labels: feature

#292 ⬆️ Bump react from 17 to 18
  package.json
  src/index.tsx
  yarn.lock
Labels: dependencies

#293 ⬆️ Bump babel, eslint & postcss to latest version
  .babelrc
  .eslintrc.json
  package.json
  yarn.lock
Labels: dependencies

#294 ✨ Add Telegram Support
  src/api/Ticker.ts
  src/components/TelegramCard.tsx
  src/components/TelegramForm.tsx
  src/components/TelegramModalForm.tsx
  src/views/TickerView.tsx
Labels: feature

#307 🐛 Fix undefined location in TickerForm
  src/components/TickerForm.tsx
Labels: bug
